# Generated by Django 2.0.7 on 2020-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
