# Generated by Django 3.0.5 on 2020-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0005_auto_20200416_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.TextField(default='Anonymous Dad'),
        ),
    ]
