# Generated by Django 2.0.7 on 2020-04-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0010_auto_20200423_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
