# Generated by Django 2.1.5 on 2020-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0013_joke_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='override',
            field=models.BooleanField(default=False),
        ),
    ]
